version: "3.8"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    environment:
      POSTGRES_DB: rentx
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: ignite
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres

volumes:
    pgdata:
      driver: local